export const UTM_SOURCE = 'jumper';

/*
  Name of an action that a user makes on the site.
  GA: in GA this is the name of the event that is fired
*/
export enum TrackingAction {
  // WalletMenu
  ConnectWallet = 'action_connect_wallet',
  ClickConnectWallet = 'action_click_connect_wallet',
  CopyAddressToClipboard = 'action_copy_addr_to_clipboard',
  DisconnectWallet = 'action_disconnect_wallet',
  OpenBlockchainExplorer = 'action_open_blockchain_explorer',
  SwitchChain = 'action_switch_chain',

  // Widget
  OnRouteSelected = 'action_on_route_selected',
  OnRouteExecutionStarted = 'action_on_route_exec_started',
  OnRouteExecutionCompleted = 'action_on_route_exec_completed',
  OnRouteExecutionFailed = 'action_on_route_exec_failed',
  OnRouteExecutionUpdated = 'action_on_route_exec_updated',
  OnRouteHighValueLoss = 'action_on_route_high_value_loss',
  OnSourceChainAndTokenSelection = 'action_on_source_selection',
  OnDestinationChainAndTokenSelection = 'action_on_destination_selection',
  OnWidgetExpanded = 'action_on_widget_expanded',
  OnAvailableRoutes = 'action_available_routes',
  OnTokenSearch = 'action_token_search',
  OnLowAddressActivityConfirmed = 'action_on_low_address_activity_confirmed',
  OnChangeSettings = 'action_change_settings',
  ClickContribute = 'action_contribute',
  ContributeImpression = 'action_contribute_impression',
  ContributeSuccess = 'action_contribute_success',
  OnChainPinned = 'action_on_chain_pinned',
  OnSendToWalletToggled = 'action_on_send_to_wallet_toggled',
  OnFormFieldChanged = 'action_on_form_field_changed',

  // Welcome_Screen
  ShowWelcomeMessageScreen = 'action_show_welcome_screen',
  CloseWelcomeScreen = 'action_close_welcome_screen',
  OpenToolModal = 'action_open_stats_modal',
  OpenWelcomeMessageLink = 'action_open_welcome_message_link',

  // Feature Card
  ClickFeatureCard = 'action_click_feature_card',
  CloseFeatureCard = 'action_close_feature_card',
  DisplayFeatureCard = 'action_display_feature_card',

  // Menu
  OpenMenu = 'action_open_submenu',
  PageLoad = 'action_pageload',
  SwitchLanguage = 'action_switch_language',
  SwitchTab = 'action_switch_tab',
  SwitchTheme = 'action_switch_theme',
  SwitchThemeTemplate = 'action_switch_theme_template',
  DownloadBrandAssets = 'action_dl_brand_assets',
  ClickConnectToWidget = 'action_click_connect_to_jumper',
  ClickXLink = 'action_click_x_link',
  ClickDiscordLink = 'action_click_discord_link',
  ClickTelegramLink = 'action_click_telegram_link',
  ClickLink3Link = 'action_click_link3_link',
  ClickJumperExchangeLink = 'action_click_jumper_exchange_link',
  ClickJumperPrivacyPolicyLink = 'action_click_jumper_privacy_policy_link',
  ClickJumperTermsConditionsLink = 'action_click_jumper_terms_conditions_link',

  // Discord
  JoinDiscordCommunity = 'action_join_discord_community',
  OpenDiscordSupport = 'action_open_discord_support',
  PoweredBy = 'action_click_powered_by',
}

export enum TrackingEventDataAction {
  ExecutionStart = 'execution_start',
  ExecutionUpdated = 'execution_updated',
  ExecutionCompleted = 'execution_completed',
  ExecutionFailed = 'execution_failed',
}

export enum TrackingCategory {
  MainMenu = 'cat_main_menu',
  Menu = 'cat_menu',
  ErrorPage = 'cat_error_page',
  FeatureCard = 'cat_feature_card',
  Navigation = 'cat_navigation',
  LanguageMenu = 'cat_language_menu',
  ThemesMenu = 'cat_themes_menu',
  SubMenu = 'cat_submenu',
  ThemeSection = 'cat_theme_section',
  DiscordBanner = 'cat_discord_banner',
  Wallet = 'cat_wallet',
  WalletMenu = 'cat_wallet_menu',
  AddressMenu = 'cat_address_menu',
  Connect = 'cat_connect_wallet',
  Pageload = 'cat_pageload',
  WalletSelectMenu = 'cat_wallet_select_menu',
  WelcomeScreen = 'cat_welcome_screen',
  Widget = 'cat_widget',
  WidgetEvent = 'cat_widget_event',
  PoweredBy = 'cat_powered_by',
}

// can be used as custom dimensions / metrics
export enum TrackingEventParameter {
  FeatureCardTitle = 'param_feature_card_title',
  FeatureCardId = 'param_feature_card_id',
  Tab = 'param_tab',
  ChainId = 'param_chain_id',
  Menu = 'param_menu',
  ToolModal = 'param_stats_modal',
  WelcomeMessageLink = 'param_welcome_message_link',
  SwitchedChain = 'param_switched_chain',
  SwitchedTheme = 'param_switched_theme',
  SwitchedTemplate = 'param_switched_template',
  SwitchedLanguage = 'param_switched_language',
  Wallet = 'param_wallet',
  WalletAddress = 'param_wallet_address',
  WalletAddresses = 'param_wallet_addresses',
  Ecosystem = 'param_ecosystem',
  Integrator = 'param_integrator',

  // Widget:
  SourceChainSelection = 'param_source_chain',
  SourceTokenSelection = 'param_source_token',
  DestinationChainSelection = 'param_destination_chain',
  DestinationTokenSelection = 'param_destination_token',
  GasPriceSettings = 'param_gas_price',
  SlippageLevelSettings = 'param_slippage_level',
  SlippageStatusSettings = 'param_slippage_status',
  RoutePrioritySettings = 'param_route_priority',
  EnableAutoRefuelSettings = 'param_enable_auto_refuel',
  EnabledBridgesSettings = 'param_enabled_bridges',
  EnabledExchangesSettings = 'param_enabled_exchanges',
  DisabledBridgesSettings = 'param_disabled_bridges',
  DisabledExchangesSettings = 'param_disabled_exchanges',
  UpdatedSetting = 'param_updated_setting',
  NewSettingValue = 'param_new_setting_value',
  PreviousSettingValue = 'param_previous_setting_value',
  Pinned = 'param_pinned',
  SendToWallet = 'param_send_to_wallet',
  Page = 'param_page',
  FormField = 'param_form_field',
  NewValue = 'param_new_value',
  PreviousValue = 'param_previous_value',

  // Pageload:
  PageloadSource = 'param_pageload_source',
  PageloadURL = 'param_pageload_url',
  PageloadDestination = 'param_pageload_destination',
  PageloadExternal = 'param_pageload_external',

  // Selection:
  RoutePosition = 'param_route_position',

  // Transaction:
  Action = 'param_action',
  ErrorCode = 'param_error_code',
  ErrorCodeKey = 'param_error_code_key',
  ErrorMessage = 'param_error_message',
  FeeCost = 'param_fee_cost',
  FeeCostFormatted = 'param_fee_cost_formatted',
  FeeCostUSD = 'param_fee_cost_usd',
  FromAmount = 'param_from_amount',
  FromAmountUSD = 'param_from_amount_usd',
  FromToken = 'param_from_token',
  FromChainId = 'param_from_chain_id',
  LastStepAction = 'param_last_step_action',
  Error = 'param_error',
  Exchange = 'param_exchange',
  GasCost = 'param_gas_cost',
  GasCostFormatted = 'param_gas_cost_formatted',
  GasCostUSD = 'param_gas_cost_usd',
  IsFinal = 'param_is_final',
  Message = 'param_message',
  NbOfSteps = 'param_nb_of_steps',
  RouteId = 'param_route_id',
  Routes = 'param_routes',
  SessionId = 'param_session_id',
  Slippage = 'param_slippage',
  MaxSlippage = 'param_max_slippage',
  Status = 'param_status',
  StepIds = 'param_step_ids',
  Steps = 'param_steps',
  ToToken = 'param_to_token',
  ToChainId = 'param_to_chain_id',
  Timestamp = 'param_timestamp',
  Tags = 'param_tags',
  Time = 'param_time',
  ToAmount = 'param_to_amount',
  ToAmountFormatted = 'param_to_amount_formatted',
  ToAmountUSD = 'param_to_amount_usd',
  ToAmountMin = 'param_to_amount_min',
  TransactionId = 'param_transaction_id',
  TransactionHash = 'param_transaction_hash',
  TransactionLink = 'param_transaction_link',
  TransactionStatus = 'param_transaction_status',
  Type = 'param_type',
  ValueLoss = 'param_value_loss',
}
